### ISSUE TITLE
Creating project results in errors

### ISSUE THREAD

**Issue by KevinBurton** [thriveweb/yellowcake#53]
### Reproduction

`gatsby new yellowcake https://github.com/thriveweb/yellowcake`

### Errors

```
PS C:\Users\RKevi\source\repos> gatsby new yellowcake https://github.com/thriveweb/yellowcake
info Creating new site from git: https://github.com/thriveweb/yellowcake.git
Cloning into 'yellowcake'...
remote: Enumerating objects: 132, done.
remote: Counting objects: 100% (132/132), done.
remote: Compressing objects: 100% (116/116), done.
remote: Total 132 (delta 19), reused 75 (delta 13), pack-reused 0
Receiving objects: 100% (132/132), 751.48 KiB | 820.00 KiB/s, done.
Resolving deltas: 100% (19/19), done.
←[32msuccess←[39m Created starter directory layout
←[34minfo←[39m Installing packages...
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.1: The platform "win32" is incompatible with this module.
info "fsevents@2.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "gatsby > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning "gatsby-plugin-netlify > webpack-assets-manifest@3.1.1" has unmet peer dependency "webpack@>=4.4.0".
warning "gatsby-plugin-sass > sass-loader@7.3.1" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
warning "netlify-cms-app > netlify-cms-widget-markdown > slate-edit-list@0.11.3" has incorrect peer dependency "slate@^0.32.0".
warning "netlify-cms-app > netlify-cms-widget-markdown > slate-edit-table@0.15.2" has incorrect peer dependency "slate@^0.33.3".
warning "netlify-cms-app > netlify-cms-widget-markdown > slate-edit-table@0.15.2" has unmet peer dependency "slate-schema-violations@^0.1.7".
warning "netlify-cms-app > netlify-cms-core > redux-notifications > react-redux@4.4.10" has incorrect peer dependency "redux@^2.0.0 || ^3.0.0".
[4/4] Building fresh packages...
[-/13] ⠈ waiting...
[6/13] ⠈ sharp
[7/13] ⠈ node-sass
[-/13] ⠈ waiting...
error C:\Users\RKevi\source\repos\yellowcake\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\Users\RKevi\source\repos\yellowcake\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe C:\Users\RKevi\source\repos\yellowcake\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\RKevi\\source\\repos\\yellowcake\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.4.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\RKevi\source\repos\yellowcake\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\RKevi\source\repos\yellowcake\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\RKevi\source\repos\yellowcake\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\RKevi\source\repos\yellowcake\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\RKevi\source\repos\yellowcake\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\RKevi\source\repos\yellowcake\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:175:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\RKevi\source\repos\yellowcake\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\RKevi\source\repos\yellowcake\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\RKevi\source\repos\yellowcake\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\RKevi\source\repos\yellowcake\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\RKevi\source\repos\yellowcake\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\RKevi\source\repos\yellowcake\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:175:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python27\python.EXE
gyp verb check python version `C:\Python27\python.EXE -c "import sys; print "2.7.17
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 14.4.0
gyp verb command install [ '14.4.0' ]
gyp verb install input version string "14.4.0"
gyp verb install installing version: 14.4.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 14.4.0
gyp verb build dir attempting to create "build" dir: C:\Users\RKevi\source\repos\yellowcake\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? C:\Users\RKevi\source\repos\yellowcake\node_modules\node-sass\build
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.18362
gyp verb find vs2017   - Using this installation with Windows 10 SDK
gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Users\RKevi\source\repos\yellowcake\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\RKevi\source\repos\yellowcake\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\RKevi\source\repos\yellowcake\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [
gyp info spawn args   'C:\\Users\\RKevi\\source\\repos\\yellowcake\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\RKevi\\source\\repos\\yellowcake\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\RKevi\\source\\repos\\yellowcake\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\RKevi\\.node-gyp\\14.4.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\RKevi\\.node-gyp\\14.4.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\RKevi\\source\\repos\\yellowcake\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\RKevi\\.node-gyp\\14.4.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\RKevi\\source\\repos\\yellowcake\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\RKevi\\source\\repos\\yellowcake\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\RKevi\.node-gyp\14.4.0
gyp verb found first Solution file build/binding.sln
gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:468:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\RKevi\\source\\repos\\yellowcake\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\RKevi\source\repos\yellowcake\node_modules\node-sass
gyp ERR! node -v v14.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.





 ERROR

Command failed with exit code 1: yarnpkg



  Error: Command failed with exit code 1: yarnpkg

  - error.js:56 makeError
    [npm]/[gatsby-cli]/[execa]/lib/error.js:56:11

  - index.js:114 handlePromise
    [npm]/[gatsby-cli]/[execa]/index.js:114:26

  - task_queues.js:97 processTicksAndRejections
    internal/process/task_queues.js:97:5

  - init-starter.js:136 async install
    [npm]/[gatsby-cli]/lib/init-starter.js:136:7

  - init-starter.js:206 async clone
    [npm]/[gatsby-cli]/lib/init-starter.js:206:3

  - init-starter.js:345 async initStarter
    [npm]/[gatsby-cli]/lib/init-starter.js:345:19

  - create-cli.js:400
    [npm]/[gatsby-cli]/lib/create-cli.js:400:7
```

### Environment

  System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i7-4610M CPU @ 3.00GHz
  Binaries:
    Node: 14.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17
  Browsers:
    Edge: 44.19041.1.0
  npmGlobalPackages:
    gatsby-cli: 2.12.60

**Comment by Firthir** [comment]
See .nvmrc file to show you the version of node that is required. Currently set at 13.

**Comment by KevinBurton** [comment]
Alex,

Thank you.

I am using v14.4.0 as reported by node-v. It just be something else.

Kevin

**Comment by Firthir** [comment]
Check out Node Version Manager this will allow you to switch versions. https://github.com/nvm-sh/nvm

**Comment by KevinBurton** [comment]
I am not using nvm.

**Comment by Firthir** [comment]
I would recommend it. Very useful tool.

**Comment by KevinBurton** [comment]
I understand the reasons for using it but are you indicating that one
should use nvm to use this template?
